@extends('layouts.dashboard')
@section('title','Wallet')
@section('content')
<div class="dashboard-heading"><div><div class="eyebrow"><span class="live-pulse"></span>Wallet</div><h1>Your wallet</h1><p>Manage funding records, bank details and deposit verification from one workspace.</p></div><a href="{{ route('withdraw') }}" class="btn dashboard-primary-btn"><i class="bi bi-arrow-up-right me-2"></i>Withdraw</a></div>
<div class="row g-3 mb-3"><div class="col-md-6 col-xl-4"><div class="stat-card"><div class="stat-icon"><i class="bi bi-wallet2"></i></div><div class="stat-label">Available balance</div><div class="stat-value">{{ $investor->curAbbr }}{{ number_format($investor->Total_Deposit*(float)$investor->exchangerate,2) }}</div><div class="stat-foot"><span class="status-dot"></span>Portfolio funding balance</div></div></div><div class="col-md-6 col-xl-4"><div class="stat-card"><div class="stat-icon"><i class="bi bi-arrow-down-circle"></i></div><div class="stat-label">Deposits recorded</div><div class="stat-value">{{ $deposits->count() }}</div><div class="stat-foot">Funding history entries</div></div></div><div class="col-md-6 col-xl-4"><div class="stat-card"><div class="stat-icon"><i class="bi bi-bank"></i></div><div class="stat-label">Banking</div><div class="stat-value">Secure</div><div class="stat-foot">Add or update your payout details</div></div></div></div>
<div class="row g-3"><div class="col-lg-5"><div class="dashboard-panel h-100"><div class="section-kicker">Payout settings</div><h2>Add bank account</h2><form id="bankForm" class="modern-form mt-4">@csrf<div class="form-group"><label>Bank name</label><input name="bank_name" class="form-control" required></div><div class="form-group"><label>Account name</label><input name="account_name" class="form-control" required></div><div class="form-group"><label>Account number</label><input name="account_number" class="form-control" required></div><div class="form-group"><label>Routing number <span>(optional)</span></label><input name="routing_number" class="form-control"></div><button class="btn dashboard-primary-btn w-100">Save bank account</button></form></div></div>
<div class="col-lg-7"><div class="dashboard-panel mb-3"><div class="section-kicker">Funding verification</div><h2>Upload deposit proof</h2><p class="text-muted small mt-2">Submit a clear image of your deposit proof for review.</p><form id="proofForm" class="modern-form mt-3" enctype="multipart/form-data">@csrf<input name="proof_image" type="file" accept=".jpg,.jpeg,.png,.gif" class="form-control" required><button class="btn btn-outline-secondary mt-3">Upload proof</button></form></div><div class="dashboard-panel"><div class="panel-heading"><div><div class="section-kicker">History</div><h2>Recent deposits</h2></div></div>@forelse($deposits as $d)<div class="cash-row"><span class="cash-icon positive"><i class="bi bi-arrow-down-left"></i></span><div><strong>Deposit</strong><small>{{ $d->Date }}</small></div><b>{{ $investor->curAbbr }}{{ number_format($d->Amount_Deposited*(float)$investor->exchangerate,2) }}</b></div>@empty<div class="empty-mini"><i class="bi bi-inbox"></i>No deposits recorded.</div>@endforelse</div></div></div>
@endsection
@push('scripts')<script>
document.getElementById('bankForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('{{ route('ajax.bank') }}',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))});alert(d.message);e.target.reset()}catch(x){alert(x.message)}};
document.getElementById('proofForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('{{ route('ajax.proof') }}',{method:'POST',body:new FormData(e.target)});alert(d.message);e.target.reset()}catch(x){alert(x.message)}};
</script>@endpush