@extends('layouts.dashboard')
@section('title','Start Investment')
@section('content')
<div class="dashboard-heading"><div><div class="eyebrow"><i class="bi bi-lightning-charge-fill"></i> Investment setup</div><h1>Start {{ $plan->name }}</h1><p>Choose an amount to start this investment.</p></div><a href="{{ route('dashboard.ira') }}" class="dashboard-primary-btn text-decoration-none"><i class="bi bi-arrow-left me-1"></i> Back to IRA</a></div>
<div class="row g-4"><div class="col-xl-7"><div class="dashboard-panel h-100 investment-start-panel"><div class="d-flex justify-content-between gap-3"><div>@if($plan->featured)<span class="plan-badge">Popular</span>@endif<div class="investment-plan-icon mt-3"><i class="bi bi-pie-chart-fill"></i></div><h2 class="mt-3">{{ $plan->name }}</h2><p class="text-muted">{{ $plan->description }}</p></div><span class="risk-pill">{{ $plan->risk_level }} risk</span></div>
<div class="investment-facts mt-4"><div><span>Minimum</span><strong>${{ number_format($plan->minimum_amount,2) }}</strong></div><div><span>Maximum</span><strong>{{ $plan->maximum_amount !== null ? '$'.number_format($plan->maximum_amount,2) : 'No limit' }}</strong></div><div><span>Term</span><strong>{{ $plan->term_label }}</strong></div><div><span>Duration</span><strong>{{ $plan->duration_days }} days</strong></div></div>
<ul class="plan-list mt-4">@foreach(($plan->features ?? []) as $feature)<li><i class="bi bi-check-circle-fill"></i>{{ $feature }}</li>@endforeach</ul></div></div>
<div class="col-xl-5"><div class="dashboard-panel h-100"><div class="section-kicker">Funding</div><h2>Choose investment amount</h2><div class="balance-card mt-3"><span>Available balance</span><strong>{{ $investor->curAbbr ?? '$' }}{{ number_format((float)$investor->Total_Deposit * (float)($investor->exchangerate ?: 1),2) }}</strong></div>
<form id="investForm" class="modern-form mt-4">@csrf<input type="hidden" name="plan_id" value="{{ $plan->id }}"><div class="form-group"><label>Investment amount</label><div class="input-shell"><i class="bi bi-cash-stack"></i><input name="amount" type="number" step="0.01" min="{{ $plan->minimum_amount }}" @if($plan->maximum_amount !== null) max="{{ $plan->maximum_amount }}" @endif required></div><small>Minimum ${{ number_format($plan->minimum_amount,2) }}{{ $plan->maximum_amount !== null ? ' · Maximum $'.number_format($plan->maximum_amount,2) : '' }}</small></div>
<div class="confirmation-box mt-3"><i class="bi bi-shield-check"></i><span>The server verifies your balance before the debit is made.</span></div><div id="msg" class="small mt-3" role="alert"></div><button id="submitBtn" type="submit" class="btn dashboard-primary-btn w-100 mt-2"><i class="bi bi-lightning-charge-fill me-2"></i>Start investment</button></form></div></div></div>
@endsection
@push('head')<style>.investment-start-panel{background:radial-gradient(circle at 90% 10%,rgba(40,100,255,.12),transparent 35%),var(--db-panel)}.investment-plan-icon{width:62px;height:62px;border-radius:18px;display:flex;align-items:center;justify-content:center;background:rgba(40,100,255,.12);color:#4d8dff;font-size:1.55rem}.risk-pill{font-size:.64rem;font-weight:800;padding:7px 10px;border-radius:999px;border:1px solid var(--db-border);color:var(--db-muted);white-space:nowrap}.investment-facts{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.investment-facts>div{padding:14px;border:1px solid var(--db-border);border-radius:12px}.investment-facts span,.investment-facts strong{display:block}.investment-facts span{font-size:.62rem;color:var(--db-muted)}.investment-facts strong{font-size:.86rem;margin-top:5px}.balance-card{padding:16px;border-radius:14px;background:rgba(40,100,255,.08);border:1px solid rgba(40,100,255,.18)}.balance-card span,.balance-card strong{display:block}.balance-card span{font-size:.65rem;color:var(--db-muted)}.balance-card strong{font-size:1.35rem;margin-top:4px}.confirmation-box{display:flex;gap:10px;padding:12px;border-radius:12px;background:rgba(40,100,255,.05);border:1px solid var(--db-border)}.confirmation-box i{color:#4d8dff}.confirmation-box span{font-size:.65rem;color:var(--db-muted)}</style>@endpush
@push('scripts')<script>document.getElementById('investForm').addEventListener('submit',async function(e){e.preventDefault();const b=document.getElementById('submitBtn'),m=document.getElementById('msg');b.disabled=true;m.textContent='Checking balance and starting investment...';try{const d=await api('{{ route('investments.store') }}',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(this))});m.innerHTML='<span class="text-success">'+d.message+'</span>';setTimeout(()=>location.href=d.redirect,500)}catch(x){m.innerHTML='<span class="text-danger">'+x.message+'</span>';b.disabled=false}})</script>@endpush