<?php
return ['pages' => [
    'manualloadreferral' => [
        'title' => 'Manual Load Referral',
        'legacy' => 'ManualLoadReferral.php',
        'table' => 'refferals',
        'kind' => 'endpoint',
    ],
    'deletewallet' => [
        'title' => 'Delete Wallet',
        'legacy' => 'DeleteWallet.php',
        'table' => 'walletaddress',
        'kind' => 'endpoint',
    ],
    'sendbulkmail' => [
        'title' => 'Send Bulk Mail',
        'legacy' => 'SendBulkMail.php',
        'table' => 'email',
        'kind' => 'page',
    ],
    'addstock' => [
        'title' => 'Add Stock',
        'legacy' => 'AddStock.php',
        'table' => 'stock',
        'kind' => 'page',
    ],
    'mystocks' => [
        'title' => 'My Stocks',
        'legacy' => 'MyStocks.php',
        'table' => 'stock',
        'kind' => 'page',
    ],
    'addwallet' => [
        'title' => 'Add Wallet',
        'legacy' => 'AddWallet.php',
        'table' => 'walletaddress',
        'kind' => 'endpoint',
    ],
    'selecttraders' => [
        'title' => 'Select Traders',
        'legacy' => 'SelectTraders.php',
        'table' => 'copy_traders',
        'kind' => 'page',
    ],
    'header' => [
        'title' => 'Header',
        'legacy' => 'Header.php',
        'table' => null,
        'kind' => 'page',
    ],
    'verification' => [
        'title' => 'Verification',
        'legacy' => 'Verification.php',
        'table' => 'verification',
        'kind' => 'page',
    ],
    'manualverify' => [
        'title' => 'Manual Verify',
        'legacy' => 'ManualVerify.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'updatesitename' => [
        'title' => 'Update Site Name',
        'legacy' => 'updateSiteName.php',
        'table' => 'sitename',
        'kind' => 'endpoint',
    ],
    'reducedepositloader' => [
        'title' => 'Reduce Deposit Loader',
        'legacy' => 'ReduceDepositLoader.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'updatedesc' => [
        'title' => 'Update Desc',
        'legacy' => 'updateDesc.php',
        'table' => 'investmentplans',
        'kind' => 'endpoint',
    ],
    'settledueinvestments' => [
        'title' => 'Settle Due Investments',
        'legacy' => 'SettleDueInvestments.php',
        'table' => 'contracts',
        'kind' => 'endpoint',
    ],
    'lock' => [
        'title' => 'Lock',
        'legacy' => 'Lock.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'selectfaq' => [
        'title' => 'Select Faq',
        'legacy' => 'SelectFaq.php',
        'table' => 'faq',
        'kind' => 'page',
    ],
    'myclients' => [
        'title' => 'My Clients',
        'legacy' => 'MyClients.php',
        'table' => 'investors',
        'kind' => 'page',
    ],
    'agentprofile' => [
        'title' => 'Agent Profile',
        'legacy' => 'AgentProfile.php',
        'table' => 'agent',
        'kind' => 'page',
    ],
    'makeactive' => [
        'title' => 'Make Active',
        'legacy' => 'MakeActive.php',
        'table' => 'walletaddress',
        'kind' => 'endpoint',
    ],
    'manualreferralloader' => [
        'title' => 'Manual Referral Loader',
        'legacy' => 'ManualReferralLoader .php',
        'table' => null,
        'kind' => 'page',
    ],
    'deposit' => [
        'title' => 'Deposit',
        'legacy' => 'Deposit.php',
        'table' => 'deposits',
        'kind' => 'endpoint',
    ],
    'searchmodal' => [
        'title' => 'Search Modal',
        'legacy' => 'SearchModal.php',
        'table' => null,
        'kind' => 'page',
    ],
    'action' => [
        'title' => 'Action',
        'legacy' => 'action.php',
        'table' => 'investors',
        'kind' => 'page',
    ],
    'loginmodal' => [
        'title' => 'Login Modal',
        'legacy' => 'LoginModal.php',
        'table' => null,
        'kind' => 'page',
    ],
    'editcontent' => [
        'title' => 'Edit Content',
        'legacy' => 'EditContent.php',
        'table' => 'pages',
        'kind' => 'page',
    ],
    'delete' => [
        'title' => 'Delete',
        'legacy' => 'Delete.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'reducedeposit' => [
        'title' => 'Reduce Deposit',
        'legacy' => 'ReduceDeposit.php',
        'table' => null,
        'kind' => 'page',
    ],
    'processstock' => [
        'title' => 'Process Stock',
        'legacy' => 'ProcessStock.php',
        'table' => 'stock',
        'kind' => 'endpoint',
    ],
    'insertpost' => [
        'title' => 'Insert Post',
        'legacy' => 'insertPost.php',
        'table' => 'pages',
        'kind' => 'endpoint',
    ],
    'level' => [
        'title' => 'Level',
        'legacy' => 'Level.php',
        'table' => 'investors',
        'kind' => 'page',
    ],
    'deletefaq' => [
        'title' => 'Delete Faq',
        'legacy' => 'DeleteFaq.php',
        'table' => 'faq',
        'kind' => 'endpoint',
    ],
    'updatepage' => [
        'title' => 'Update Page',
        'legacy' => 'UpdatePage.php',
        'table' => 'pages',
        'kind' => 'endpoint',
    ],
    'selectcategory' => [
        'title' => 'Select Category',
        'legacy' => 'SelectCategory.php',
        'table' => 'menuitems',
        'kind' => 'endpoint',
    ],
    'reduceprofitloader' => [
        'title' => 'Reduce Profit Loader',
        'legacy' => 'ReduceProfitLoader.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'deleteresources' => [
        'title' => 'Delete Resources',
        'legacy' => 'deleteResources.php',
        'table' => 'resources',
        'kind' => 'endpoint',
    ],
    'updatewhatsapp' => [
        'title' => 'Update Whats App',
        'legacy' => 'updateWhatsApp.php',
        'table' => 'whatsapp',
        'kind' => 'endpoint',
    ],
    'individual-percentage' => [
        'title' => 'Individual Percentage',
        'legacy' => 'Individual_Percentage.php',
        'table' => null,
        'kind' => 'page',
    ],
    'mytraders' => [
        'title' => 'My Traders',
        'legacy' => 'MyTraders.php',
        'table' => 'copy_traders',
        'kind' => 'page',
    ],
    'getnumber' => [
        'title' => 'Get Number',
        'legacy' => 'getNumber.php',
        'table' => 'WhatsApp',
        'kind' => 'endpoint',
    ],
    'clientupload' => [
        'title' => 'Client Upload',
        'legacy' => 'ClientUpload.php',
        'table' => 'testimonials',
        'kind' => 'endpoint',
    ],
    'pushto3' => [
        'title' => 'Push To3',
        'legacy' => 'PushTo3.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'updateaboutus' => [
        'title' => 'Update About Us',
        'legacy' => 'updateAboutUs.php',
        'table' => 'aboutus',
        'kind' => 'endpoint',
    ],
    'footer' => [
        'title' => 'Footer',
        'legacy' => 'Footer.php',
        'table' => null,
        'kind' => 'page',
    ],
    'addverificationlevel' => [
        'title' => 'Add Verification Level',
        'legacy' => 'AddVerificationLevel.php',
        'table' => 'verification',
        'kind' => 'endpoint',
    ],
    'deletemail' => [
        'title' => 'Delete Mail',
        'legacy' => 'DeleteMail.php',
        'table' => 'email',
        'kind' => 'endpoint',
    ],
    'deletepage' => [
        'title' => 'Delete Page',
        'legacy' => 'DeletePage.php',
        'table' => 'pages',
        'kind' => 'endpoint',
    ],
    'loadprofit' => [
        'title' => 'Load Profit',
        'legacy' => 'LoadProfit.php',
        'table' => null,
        'kind' => 'page',
    ],
    'pages' => [
        'title' => 'Pages',
        'legacy' => 'Pages.php',
        'table' => 'pages',
        'kind' => 'page',
    ],
    'referralloader' => [
        'title' => 'Referral Loader',
        'legacy' => 'ReferralLoader.php',
        'table' => 'refferals',
        'kind' => 'page',
    ],
    'deletetoken' => [
        'title' => 'Delete Token',
        'legacy' => 'DeleteToken.php',
        'table' => 'autorization_token',
        'kind' => 'endpoint',
    ],
    'updatesignal' => [
        'title' => 'Update Signal',
        'legacy' => 'UpdateSignal.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'deletepost' => [
        'title' => 'Delete Post',
        'legacy' => 'DeletePost.php',
        'table' => null,
        'kind' => 'endpoint',
    ],
    'updatelevel' => [
        'title' => 'Update Level',
        'legacy' => 'updateLevel.php',
        'table' => 'VerificationDocs',
        'kind' => 'endpoint',
    ],
    'investmentplan' => [
        'title' => 'Investment Plan',
        'legacy' => 'InvestmentPlan.php',
        'table' => 'investmentplans',
        'kind' => 'page',
    ],
    'load-tesla' => [
        'title' => 'Load Tesla',
        'legacy' => 'load_tesla.php',
        'table' => null,
        'kind' => 'page',
    ],
    'loadreferral' => [
        'title' => 'Load Referral',
        'legacy' => 'LoadReferral.php',
        'table' => 'refferals',
        'kind' => 'endpoint',
    ],
    'addemail' => [
        'title' => 'Add Email',
        'legacy' => 'AddEmail.php',
        'table' => 'email',
        'kind' => 'endpoint',
    ],
    'profitloader' => [
        'title' => 'Profit Loader',
        'legacy' => 'ProfitLoader.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'deleteverification' => [
        'title' => 'Delete Verification',
        'legacy' => 'DeleteVerification.php',
        'table' => 'verification',
        'kind' => 'endpoint',
    ],
    'updatewalletaddress' => [
        'title' => 'Update Wallet Address',
        'legacy' => 'UpdateWalletAddress.php',
        'table' => 'walletaddress',
        'kind' => 'endpoint',
    ],
    'approve' => [
        'title' => 'Approve',
        'legacy' => 'Approve.php',
        'table' => 'contracts',
        'kind' => 'endpoint',
    ],
    'sendmail' => [
        'title' => 'Send Mail',
        'legacy' => 'SendMail.php',
        'table' => 'this',
        'kind' => 'page',
    ],
    'addplan' => [
        'title' => 'Add Plan',
        'legacy' => 'AddPlan.php',
        'table' => 'investmentplans',
        'kind' => 'endpoint',
    ],
    'generatetoken' => [
        'title' => 'Generate Token',
        'legacy' => 'GenerateToken.php',
        'table' => 'autorization_token',
        'kind' => 'endpoint',
    ],
    'manualreferralloader-2' => [
        'title' => 'Manual Referral Loader',
        'legacy' => 'ManualReferralLoader.php',
        'table' => null,
        'kind' => 'page',
    ],
    'processpayment' => [
        'title' => 'Process Payment',
        'legacy' => 'processPayment.php',
        'table' => 'withdrawals',
        'kind' => 'endpoint',
    ],
    'manipulate' => [
        'title' => 'Manipulate',
        'legacy' => 'Manipulate.php',
        'table' => 'stock',
        'kind' => 'page',
    ],
    'addinvestmentamount' => [
        'title' => 'Add Investment Amount',
        'legacy' => 'AddInvestmentAmount.php',
        'table' => 'investmentplans',
        'kind' => 'page',
    ],
    'chat' => [
        'title' => 'Chat',
        'legacy' => 'Chat.php',
        'table' => 'chat',
        'kind' => 'page',
    ],
    'mywallets' => [
        'title' => 'My Wallets',
        'legacy' => 'MyWallets.php',
        'table' => 'walletaddress',
        'kind' => 'page',
    ],
    'deletecontract' => [
        'title' => 'Delete Contract',
        'legacy' => 'DeleteContract.php',
        'table' => 'contracts',
        'kind' => 'endpoint',
    ],
    'opencontents' => [
        'title' => 'Open Contents',
        'legacy' => 'openContents.php',
        'table' => null,
        'kind' => 'page',
    ],
    'sendchat' => [
        'title' => 'Send Chat',
        'legacy' => 'sendChat.php',
        'table' => 'chats',
        'kind' => 'endpoint',
    ],
    'createpage' => [
        'title' => 'Create Page',
        'legacy' => 'CreatePage.php',
        'table' => 'pages',
        'kind' => 'endpoint',
    ],
    'logout' => [
        'title' => 'Logout',
        'legacy' => 'Logout.php',
        'table' => null,
        'kind' => 'endpoint',
    ],
    'selectemail' => [
        'title' => 'Select Email',
        'legacy' => 'SelectEmail.php',
        'table' => 'email',
        'kind' => 'page',
    ],
    'deleteverificationdoc' => [
        'title' => 'Delete Verification Doc',
        'legacy' => 'DeleteVerificationDoc.php',
        'table' => 'VerificationDocs',
        'kind' => 'endpoint',
    ],
    'siteconfig' => [
        'title' => 'Site Config',
        'legacy' => 'SiteConfig.php',
        'table' => null,
        'kind' => 'endpoint',
    ],
    'dep-tesla' => [
        'title' => 'Dep Tesla',
        'legacy' => 'dep_tesla.php',
        'table' => 'assets',
        'kind' => 'endpoint',
    ],
    'myagents' => [
        'title' => 'My Agents',
        'legacy' => 'MyAgents.php',
        'table' => 'agent',
        'kind' => 'page',
    ],
    'checkedemail' => [
        'title' => 'Checked Email',
        'legacy' => 'CheckedEmail.php',
        'table' => 'email',
        'kind' => 'page',
    ],
    'sendnotification' => [
        'title' => 'Send Notification',
        'legacy' => 'sendNotification.php',
        'table' => 'notification',
        'kind' => 'endpoint',
    ],
    'clearall' => [
        'title' => 'Clear All',
        'legacy' => 'ClearAll.php',
        'table' => null,
        'kind' => 'endpoint',
    ],
    'updateaccount' => [
        'title' => 'Update Account',
        'legacy' => 'UpdateAccount.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'unlock' => [
        'title' => 'Unlock',
        'legacy' => 'Unlock.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'deleteproofdoc' => [
        'title' => 'Delete Proof Doc',
        'legacy' => 'DeleteProofDoc.php',
        'table' => 'ProofDoc',
        'kind' => 'endpoint',
    ],
    'settle' => [
        'title' => 'Settle',
        'legacy' => 'Settle.php',
        'table' => 'contracts',
        'kind' => 'endpoint',
    ],
    'addtraders' => [
        'title' => 'Add Traders',
        'legacy' => 'AddTraders.php',
        'table' => 'copy_traders',
        'kind' => 'endpoint',
    ],
    'insertfaq' => [
        'title' => 'Insert Faq',
        'legacy' => 'insertFAQ.php',
        'table' => 'faq',
        'kind' => 'endpoint',
    ],
    'index' => [
        'title' => 'Index',
        'legacy' => 'index.php',
        'table' => null,
        'kind' => 'page',
    ],
    'uploadresources' => [
        'title' => 'Upload Resources',
        'legacy' => 'uploadResources.php',
        'table' => 'resources',
        'kind' => 'endpoint',
    ],
    'resources' => [
        'title' => 'Resources',
        'legacy' => 'Resources.php',
        'table' => 'resources',
        'kind' => 'page',
    ],
    'deleteamount' => [
        'title' => 'Delete Amount',
        'legacy' => 'deleteAmount.php',
        'table' => 'investmentplans',
        'kind' => 'endpoint',
    ],
    'insertstock' => [
        'title' => 'Insert Stock',
        'legacy' => 'insertStock.php',
        'table' => 'stock',
        'kind' => 'endpoint',
    ],
    'deletestock' => [
        'title' => 'Delete Stock',
        'legacy' => 'DeleteStock.php',
        'table' => 'stock',
        'kind' => 'endpoint',
    ],
    'login' => [
        'title' => 'Login',
        'legacy' => 'Login.php',
        'table' => 'investors',
        'kind' => 'page',
    ],
    'pushto5' => [
        'title' => 'Push To5',
        'legacy' => 'PushTo5.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'declinepayment' => [
        'title' => 'Decline Payment',
        'legacy' => 'DeclinePayment.php',
        'table' => 'investors',
        'kind' => 'endpoint',
    ],
    'allemail' => [
        'title' => 'All Email',
        'legacy' => 'AllEmail.php',
        'table' => 'email',
        'kind' => 'endpoint',
    ],
    'newpost' => [
        'title' => 'New Post',
        'legacy' => 'NewPost.php',
        'table' => 'posts',
        'kind' => 'page',
    ],
    'getmessages' => [
        'title' => 'Get Messages',
        'legacy' => 'getMessages.php',
        'table' => 'chat',
        'kind' => 'page',
    ],
    'updatewelcomenote' => [
        'title' => 'Update Welcome Note',
        'legacy' => 'updateWelcomeNote.php',
        'table' => 'welcomenote',
        'kind' => 'endpoint',
    ],
    'selectinvestmentplans' => [
        'title' => 'Select Investment Plans',
        'legacy' => 'SelectInvestmentPlans.php',
        'table' => 'investmentplans',
        'kind' => 'page',
    ],
    'updatesiteaddress' => [
        'title' => 'Update Site Address',
        'legacy' => 'updateSiteAddress.php',
        'table' => 'siteaddress',
        'kind' => 'endpoint',
    ],
    'myeditor' => [
        'title' => 'My Editor',
        'legacy' => 'MyEditor.php',
        'table' => 'pages',
        'kind' => 'page',
    ],
    'selectwallet' => [
        'title' => 'Select Wallet',
        'legacy' => 'SelectWallet.php',
        'table' => 'walletaddress',
        'kind' => 'page',
    ],
    'composemail' => [
        'title' => 'Compose Mail',
        'legacy' => 'ComposeMail.php',
        'table' => null,
        'kind' => 'page',
    ],
    'reduceprofit' => [
        'title' => 'Reduce Profit',
        'legacy' => 'ReduceProfit.php',
        'table' => null,
        'kind' => 'page',
    ],
    'faqcontainer' => [
        'title' => 'Faq Container',
        'legacy' => 'FaqContainer.php',
        'table' => null,
        'kind' => 'page',
    ],
    'deleteplan' => [
        'title' => 'Delete Plan',
        'legacy' => 'DeletePlan.php',
        'table' => null,
        'kind' => 'endpoint',
    ],
    'customizesite' => [
        'title' => 'Customize Site',
        'legacy' => 'CustomizeSite.php',
        'table' => 'aboutus',
        'kind' => 'page',
    ],
    'getcontractinfo' => [
        'title' => 'Get Contract Info',
        'legacy' => 'getContractInfo.php',
        'table' => 'contracts',
        'kind' => 'endpoint',
    ],
    'bulkmail' => [
        'title' => 'Bulk Mail',
        'legacy' => 'BulkMail.php',
        'table' => null,
        'kind' => 'page',
    ],
    'resendverificationmail' => [
        'title' => 'Resend Verification Mail',
        'legacy' => 'ResendVerificationMail.php',
        'table' => null,
        'kind' => 'page',
    ],
    'searchclient' => [
        'title' => 'Search Client',
        'legacy' => 'SearchClient.php',
        'table' => 'investors',
        'kind' => 'page',
    ],
    'deleteagent' => [
        'title' => 'Delete Agent',
        'legacy' => 'deleteAgent.php',
        'table' => 'agent',
        'kind' => 'endpoint',
    ],
]];