@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')
<div class="container-fluid px-3 px-lg-4 py-4 py-lg-5">
<div class="dashboard-heading"><div><div class="eyebrow"><span class="live-pulse"></span> Portfolio overview</div><h1>Welcome back, {{ $investor->First_Name ?? $investor->name ?? 'Trader' }}</h1><p>Monitor your portfolio, track market movement and manage your investments from one workspace.</p></div><a href="{{ route('investments.plans') }}" class="btn dashboard-primary-btn"><i class="bi bi-plus-lg me-2"></i>New investment</a></div>
<div class="row g-3 mb-4">
@php $metrics=[['Available Balance',$stats['balance'],$investor->curAbbr ?? '
@foreach($metrics as $metric)<div class="col-6 col-xl-3"><div class="stat-card h-100"><div class="stat-icon"><i class="bi {{ $metric[3] }}"></i></div><div class="stat-label">{{ $metric[0] }}</div><div class="stat-value">{{ $metric[2] }}{{ $metric[2] === '' ? number_format($metric[1]) : number_format((float)$metric[1],2) }}</div><div class="stat-foot"><span class="status-dot"></span> Account data</div></div></div>@endforeach
</div>
<div class="row g-3 mb-4">
<div class="col-12 col-xl-9"><section class="trading-card"><div class="trading-card-header"><div><div class="section-kicker">Portfolio performance</div><h2>Market overview</h2></div><div class="chart-toolbar">@foreach(['1D','1W','1M','3M','1Y'] as $range)<button type="button" class="{{ $loop->first ? 'active' : '' }}">{{ $range }}</button>@endforeach</div></div><div class="chart-summary"><div><span class="price-label">Portfolio index</span><strong id="chartLastValue">—</strong></div><div class="chart-change" id="chartChange">Available account history</div></div><div class="main-chart-wrap"><canvas id="portfolioChart"></canvas></div><div class="volume-wrap"><canvas id="volumeChart"></canvas></div><div class="chart-legend"><span><i class="legend-line"></i> Portfolio movement</span><span><i class="legend-volume"></i> Activity</span></div></section></div>
<div class="col-12 col-xl-3"><section class="market-watch-card h-100"><div class="section-kicker">Quick actions</div><h2>Trade center</h2><div class="quick-action-grid"><a href="{{ route('investments.plans') }}"><span><i class="bi bi-lightning-charge-fill"></i></span><strong>Invest</strong><small>Browse plans</small></a><a href="{{ route('deposit') }}"><span><i class="bi bi-arrow-down-left-circle-fill"></i></span><strong>Deposit</strong><small>Add funds</small></a><a href="{{ route('withdraw') }}"><span><i class="bi bi-arrow-up-right-circle-fill"></i></span><strong>Withdraw</strong><small>Move funds</small></a><a href="{{ route('transfer') }}"><span><i class="bi bi-send-fill"></i></span><strong>Transfer</strong><small>Send funds</small></a></div><div class="watchlist-title">Account status</div><div class="account-status"><div><span>Verification</span><strong><i class="bi bi-shield-check"></i> Active</strong></div><div><span>Open positions</span><strong>{{ number_format($stats['active_investments']) }}</strong></div><div><span>Notifications</span><strong>{{ ($notifications ?? collect())->count() }}</strong></div></div></section></div>
</div>
<div class="row g-3 mb-4">
<div class="col-12"><section class="dashboard-panel crypto-market-panel">
<div class="panel-heading crypto-market-heading"><div><div class="section-kicker"><span class="live-pulse"></span> Live market</div><h2>Cryptocurrency prices</h2><p class="crypto-subtitle">Live prices, 24-hour movement and 7-day market trends.</p></div><div class="crypto-market-meta"><span id="cryptoLastUpdated">Updating…</span><button type="button" class="crypto-refresh-btn" id="cryptoRefresh"><i class="bi bi-arrow-clockwise"></i> Refresh</button></div></div>
<div class="table-responsive crypto-table-wrap"><table class="table trading-table crypto-table align-middle mb-0"><thead><tr><th>Asset</th><th>Price</th><th>24h</th><th>Trend · 7D</th><th class="text-end">Trade</th></tr></thead><tbody id="cryptoMarketRows"><tr><td colspan="5"><div class="crypto-loading"><span class="spinner-border spinner-border-sm"></span> Loading live cryptocurrency prices…</div></td></tr></tbody></table></div>
<div class="crypto-mobile-list" id="cryptoMobileRows"></div>
<div class="crypto-market-foot"><span><i class="bi bi-broadcast-pin"></i> Live market data</span><span>Prices shown in USD</span></div>
</section></div></div>
<div class="row g-3">
<div class="col-12 col-xl-8"><section class="dashboard-panel"><div class="panel-heading"><div><div class="section-kicker">Positions</div><h2>Investment activity</h2></div><a href="{{ route('investments.contracts') }}" class="panel-link">View all <i class="bi bi-arrow-up-right"></i></a></div><div class="table-responsive"><table class="table trading-table align-middle"><thead><tr><th>Investment</th><th>Amount</th><th>Start date</th><th>Status</th></tr></thead><tbody>@forelse($contracts as $c)<tr><td><div class="asset-cell"><span class="asset-icon"><i class="bi bi-graph-up"></i></span><div><strong>{{ $c->Plan_Type }}</strong><small>Investment contract</small></div></div></td><td>{{ $investor->curAbbr ?? '$' }}{{ number_format((float)$c->Amount*(float)($investor->exchangerate ?? 1),2) }}</td><td>{{ $c->Contract_Start?->format('M d, Y') ?? '—' }}</td><td><span class="trade-status {{ $c->Status==1?'positive':($c->Status==2?'neutral':'pending') }}">{{ $c->Status==1?'Active':($c->Status==2?'Completed':'Pending') }}</span></td></tr>@empty<tr><td colspan="4" class="empty-state"><i class="bi bi-bar-chart-line"></i><strong>No investments yet</strong><span>Your positions will appear here.</span></td></tr>@endforelse</tbody></table></div></section></div>
</div>
</div>
@endsection
@push('head')
<style>
.crypto-market-panel{overflow:hidden}.crypto-subtitle{margin:.35rem 0 0;color:var(--db-muted);font-size:.84rem}.crypto-market-meta{display:flex;align-items:center;gap:10px;color:var(--db-muted);font-size:.76rem}.crypto-refresh-btn{border:1px solid var(--db-border);background:var(--db-surface-2);color:var(--db-text);border-radius:9px;padding:7px 10px;font-size:.76rem}.crypto-refresh-btn:hover{color:var(--db-green)}
.crypto-table{min-width:850px}.crypto-table th{font-size:.67rem;text-transform:uppercase;letter-spacing:.08em;color:var(--db-muted);font-weight:700}.crypto-table td{padding:14px 10px}.crypto-asset{display:flex;align-items:center;gap:11px;min-width:175px}.crypto-logo{width:36px;height:36px;border-radius:50%;object-fit:cover;background:var(--db-surface-2);border:1px solid var(--db-border)}.crypto-asset strong{display:block;font-size:.88rem}.crypto-asset small{display:block;color:var(--db-muted);font-size:.7rem;margin-top:2px}.crypto-price{font-weight:700;font-variant-numeric:tabular-nums;white-space:nowrap}.crypto-change{font-weight:700;font-size:.78rem;white-space:nowrap}.crypto-change.up{color:#20c997}.crypto-change.down{color:#ff6b7a}.crypto-spark{width:150px;height:46px;display:block}.crypto-actions{display:flex;justify-content:flex-end;gap:7px}.crypto-actions button{border:0;border-radius:9px;padding:7px 11px;font-size:.72rem;font-weight:700}.crypto-buy{background:rgba(40,100,255,.14);color:#4f82ff}.crypto-sell{background:rgba(255,107,122,.12);color:#ff7180}.crypto-loading{display:flex;justify-content:center;align-items:center;gap:9px;padding:30px;color:var(--db-muted)}.crypto-error{text-align:center;padding:24px;color:var(--db-muted)}.crypto-error i{display:block;font-size:1.5rem;margin-bottom:7px}.crypto-mobile-list{display:none}.crypto-market-foot{display:flex;justify-content:space-between;border-top:1px solid var(--db-border);padding:11px 16px;color:var(--db-muted);font-size:.7rem}.crypto-market-foot i{margin-right:5px;color:var(--db-green)}
@media(max-width:767.98px){.crypto-table-wrap{display:none}.crypto-mobile-list{display:block;padding:0 12px}.crypto-mobile-card{border:1px solid var(--db-border);background:var(--db-surface-2);border-radius:14px;padding:13px;margin-bottom:9px}.crypto-mobile-top,.crypto-mobile-bottom{display:flex;align-items:center;justify-content:space-between;gap:10px}.crypto-mobile-bottom{margin-top:10px}.crypto-mobile-card .crypto-spark{width:105px;height:38px}.crypto-mobile-card .crypto-actions{justify-content:flex-end}.crypto-mobile-card .crypto-actions button{padding:6px 9px}.crypto-market-meta span{display:none}}
</style>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
const rowsEl=document.getElementById('cryptoMarketRows'),mobileEl=document.getElementById('cryptoMobileRows'),refresh=document.getElementById('cryptoRefresh'),updated=document.getElementById('cryptoLastUpdated'),endpoint=@json(route('ajax.crypto'));
const money=n=>{n=Number(n);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:n<1?4:2,maximumFractionDigits:n<1?8:2}).format(n):'—'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function spark(canvas,points,up){const v=(points||[]).map(Number).filter(Number.isFinite);if(v.length<2)return;const d=window.devicePixelRatio||1,w=canvas.clientWidth||150,h=canvas.clientHeight||46;canvas.width=w*d;canvas.height=h*d;const x=canvas.getContext('2d');x.scale(d,d);const min=Math.min(...v),max=Math.max(...v),range=max-min||1;x.beginPath();v.forEach((n,i)=>{const px=i*(w/(v.length-1)),py=h-5-((n-min)/range)*(h-10);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=up?'#20c997':'#ff6b7a';x.lineWidth=2;x.lineJoin='round';x.stroke()}
function bind(){document.querySelectorAll('.crypto-spark').forEach(c=>{try{spark(c,JSON.parse(decodeURIComponent(c.dataset.points||'[]')),c.dataset.up==='1')}catch(e){}});document.querySelectorAll('.crypto-trade').forEach(b=>b.addEventListener('click',()=>alert((b.dataset.action==='buy'?'Buy ':'Sell ')+b.dataset.asset.toUpperCase()+' — live market data is connected. Crypto order execution can be connected to the wallet/order ledger next.')))}
function render(data){if(!Array.isArray(data)||!data.length){rowsEl.innerHTML='<tr><td colspan="5"><div class="crypto-error"><i class="bi bi-bar-chart"></i>No live market data is available right now.</div></td></tr>';mobileEl.innerHTML='';return}let desktop='',mobile='';data.forEach(c=>{const ch=Number(c.price_change_percentage_24h),up=ch>=0,pts=(c.sparkline_in_7d&&c.sparkline_in_7d.price)||[],name=esc(c.name),sym=esc((c.symbol||'').toUpperCase()),id=esc(c.id),img=esc(c.image||'');desktop+='<tr><td><div class="crypto-asset"><img class="crypto-logo" src="'+img+'" alt="'+name+'"><div><strong>'+name+'</strong><small>'+sym+' · #'+esc(c.market_cap_rank||'—')+'</small></div></div></td><td class="crypto-price">'+money(c.current_price)+'</td><td><span class="crypto-change '+(up?'up':'down')+'">'+(up?'+':'')+(Number.isFinite(ch)?ch.toFixed(2):'—')+'%</span></td><td><canvas class="crypto-spark" data-points="'+encodeURIComponent(JSON.stringify(pts))+'" data-up="'+(up?'1':'0')+'"></canvas></td><td><div class="crypto-actions"><button class="crypto-buy crypto-trade" data-action="buy" data-asset="'+id+'">Buy</button><button class="crypto-sell crypto-trade" data-action="sell" data-asset="'+id+'">Sell</button></div></td></tr>';mobile+='<div class="crypto-mobile-card"><div class="crypto-mobile-top"><div class="crypto-asset"><img class="crypto-logo" src="'+img+'" alt="'+name+'"><div><strong>'+name+'</strong><small>'+sym+'</small></div></div><span class="crypto-change '+(up?'up':'down')+'">'+(up?'+':'')+(Number.isFinite(ch)?ch.toFixed(2):'—')+'%</span></div><div class="crypto-mobile-bottom"><div><div class="crypto-price">'+money(c.current_price)+'</div><small style="color:var(--db-muted)">24h</small></div><canvas class="crypto-spark" data-points="'+encodeURIComponent(JSON.stringify(pts))+'" data-up="'+(up?'1':'0')+'"></canvas><div class="crypto-actions"><button class="crypto-buy crypto-trade" data-action="buy" data-asset="'+id+'">Buy</button><button class="crypto-sell crypto-trade" data-action="sell" data-asset="'+id+'">Sell</button></div></div></div>'});rowsEl.innerHTML=desktop;mobileEl.innerHTML=mobile;bind()}
async function load(){try{const r=await fetch(endpoint,{headers:{Accept:'application/json'}}),data=await r.json();if(!r.ok)throw new Error(data.message||'Market feed unavailable');render(data);if(updated)updated.textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(e){rowsEl.innerHTML='<tr><td colspan="5"><div class="crypto-error"><i class="bi bi-cloud-slash"></i>'+esc(e.message||'Market feed is temporarily unavailable.')+'</div></td></tr>';mobileEl.innerHTML='';if(updated)updated.textContent='Update failed'}}
refresh&&refresh.addEventListener('click',load);load();setInterval(load,60000);
});
</script>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
const rows=@json($chart),labels=[],values=[],volumes=[];
rows.forEach(function(row,index){const entries=Object.entries(row||{});let label=String(index+1),value=null,volume=null;entries.forEach(function(pair){const key=pair[0],raw=pair[1],lower=key.toLowerCase(),num=Number(raw);if(/date|time|created|label|day|month/.test(lower)&&raw!==null&&raw!=='')label=String(raw).slice(0,16);if(Number.isFinite(num)){if(/volume|qty|quantity|trade/.test(lower)&&volume===null)volume=num;if(/price|value|balance|portfolio|rate|close|amount/.test(lower)&&value===null)value=num;}});if(value===null){const nums=entries.map(function(p){return Number(p[1]);}).filter(Number.isFinite);if(nums.length)value=nums[nums.length-1];}if(value!==null){labels.push(label);values.push(value);volumes.push(volume===null?Math.abs(value):volume);}});
const ctx=document.getElementById('portfolioChart'),vctx=document.getElementById('volumeChart');
if(!ctx)return;
const gradient=ctx.getContext('2d').createLinearGradient(0,0,0,280);gradient.addColorStop(0,'rgba(31,199,148,.26)');gradient.addColorStop(1,'rgba(31,199,148,0)');
const options={responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{displayColors:false}},scales:{x:{grid:{display:false},ticks:{color:'#7d8799',maxTicksLimit:8}},y:{grid:{color:'rgba(130,145,170,.10)'},ticks:{color:'#7d8799'}}}};
new Chart(ctx,{type:'line',data:{labels:labels,datasets:[{data:values,borderColor:'#1fc794',backgroundColor:gradient,fill:true,borderWidth:2.5,pointRadius:0,pointHoverRadius:5,tension:.35}]},options:options});
new Chart(vctx,{type:'bar',data:{labels:labels,datasets:[{data:volumes,backgroundColor:'rgba(125,135,153,.22)',borderRadius:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}}}});
if(values.length){const last=values[values.length-1],first=values[0],delta=first?((last-first)/Math.abs(first))*100:0;document.getElementById('chartLastValue').textContent=Number(last).toLocaleString(undefined,{maximumFractionDigits:2});document.getElementById('chartChange').textContent=(delta>=0?'+':'')+delta.toFixed(2)+'% over available history';if(delta<0)document.getElementById('chartChange').classList.add('down');}
document.querySelectorAll('.chart-toolbar button').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.chart-toolbar button').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');});});
});
</script>
@endpush,'bi-wallet2'],['Portfolio Value',$stats['portfolio'],$investor->curAbbr ?? '
@foreach($metrics as $metric)<div class="col-6 col-xl-3"><div class="stat-card h-100"><div class="stat-icon"><i class="bi {{ $metric[3] }}"></i></div><div class="stat-label">{{ $metric[0] }}</div><div class="stat-value">{{ $metric[2] }}{{ $metric[2] === '' ? number_format($metric[1]) : number_format((float)$metric[1],2) }}</div><div class="stat-foot"><span class="status-dot"></span> Account data</div></div></div>@endforeach
</div>
<div class="row g-3 mb-4">
<div class="col-12 col-xl-9"><section class="trading-card"><div class="trading-card-header"><div><div class="section-kicker">Portfolio performance</div><h2>Market overview</h2></div><div class="chart-toolbar">@foreach(['1D','1W','1M','3M','1Y'] as $range)<button type="button" class="{{ $loop->first ? 'active' : '' }}">{{ $range }}</button>@endforeach</div></div><div class="chart-summary"><div><span class="price-label">Portfolio index</span><strong id="chartLastValue">—</strong></div><div class="chart-change" id="chartChange">Available account history</div></div><div class="main-chart-wrap"><canvas id="portfolioChart"></canvas></div><div class="volume-wrap"><canvas id="volumeChart"></canvas></div><div class="chart-legend"><span><i class="legend-line"></i> Portfolio movement</span><span><i class="legend-volume"></i> Activity</span></div></section></div>
<div class="col-12 col-xl-3"><section class="market-watch-card h-100"><div class="section-kicker">Quick actions</div><h2>Trade center</h2><div class="quick-action-grid"><a href="{{ route('investments.plans') }}"><span><i class="bi bi-lightning-charge-fill"></i></span><strong>Invest</strong><small>Browse plans</small></a><a href="{{ route('deposit') }}"><span><i class="bi bi-arrow-down-left-circle-fill"></i></span><strong>Deposit</strong><small>Add funds</small></a><a href="{{ route('withdraw') }}"><span><i class="bi bi-arrow-up-right-circle-fill"></i></span><strong>Withdraw</strong><small>Move funds</small></a><a href="{{ route('transfer') }}"><span><i class="bi bi-send-fill"></i></span><strong>Transfer</strong><small>Send funds</small></a></div><div class="watchlist-title">Account status</div><div class="account-status"><div><span>Verification</span><strong><i class="bi bi-shield-check"></i> Active</strong></div><div><span>Open positions</span><strong>{{ number_format($stats['active_investments']) }}</strong></div><div><span>Notifications</span><strong>{{ ($notifications ?? collect())->count() }}</strong></div></div></section></div>
</div>
<div class="row g-3 mb-4">
<div class="col-12"><section class="dashboard-panel crypto-market-panel">
<div class="panel-heading crypto-market-heading"><div><div class="section-kicker"><span class="live-pulse"></span> Live market</div><h2>Cryptocurrency prices</h2><p class="crypto-subtitle">Live prices, 24-hour movement and 7-day market trends.</p></div><div class="crypto-market-meta"><span id="cryptoLastUpdated">Updating…</span><button type="button" class="crypto-refresh-btn" id="cryptoRefresh"><i class="bi bi-arrow-clockwise"></i> Refresh</button></div></div>
<div class="table-responsive crypto-table-wrap"><table class="table trading-table crypto-table align-middle mb-0"><thead><tr><th>Asset</th><th>Price</th><th>24h</th><th>Trend · 7D</th><th class="text-end">Trade</th></tr></thead><tbody id="cryptoMarketRows"><tr><td colspan="5"><div class="crypto-loading"><span class="spinner-border spinner-border-sm"></span> Loading live cryptocurrency prices…</div></td></tr></tbody></table></div>
<div class="crypto-mobile-list" id="cryptoMobileRows"></div>
<div class="crypto-market-foot"><span><i class="bi bi-broadcast-pin"></i> Live market data</span><span>Prices shown in USD</span></div>
</section></div></div>
<div class="row g-3">
<div class="col-12 col-xl-8"><section class="dashboard-panel"><div class="panel-heading"><div><div class="section-kicker">Positions</div><h2>Investment activity</h2></div><a href="{{ route('investments.contracts') }}" class="panel-link">View all <i class="bi bi-arrow-up-right"></i></a></div><div class="table-responsive"><table class="table trading-table align-middle"><thead><tr><th>Investment</th><th>Amount</th><th>Start date</th><th>Status</th></tr></thead><tbody>@forelse($contracts as $c)<tr><td><div class="asset-cell"><span class="asset-icon"><i class="bi bi-graph-up"></i></span><div><strong>{{ $c->Plan_Type }}</strong><small>Investment contract</small></div></div></td><td>{{ $investor->curAbbr ?? '$' }}{{ number_format((float)$c->Amount*(float)($investor->exchangerate ?? 1),2) }}</td><td>{{ $c->Contract_Start?->format('M d, Y') ?? '—' }}</td><td><span class="trade-status {{ $c->Status==1?'positive':($c->Status==2?'neutral':'pending') }}">{{ $c->Status==1?'Active':($c->Status==2?'Completed':'Pending') }}</span></td></tr>@empty<tr><td colspan="4" class="empty-state"><i class="bi bi-bar-chart-line"></i><strong>No investments yet</strong><span>Your positions will appear here.</span></td></tr>@endforelse</tbody></table></div></section></div>
</div>
</div>
@endsection
@push('head')
<style>
.crypto-market-panel{overflow:hidden}.crypto-subtitle{margin:.35rem 0 0;color:var(--db-muted);font-size:.84rem}.crypto-market-meta{display:flex;align-items:center;gap:10px;color:var(--db-muted);font-size:.76rem}.crypto-refresh-btn{border:1px solid var(--db-border);background:var(--db-surface-2);color:var(--db-text);border-radius:9px;padding:7px 10px;font-size:.76rem}.crypto-refresh-btn:hover{color:var(--db-green)}
.crypto-table{min-width:850px}.crypto-table th{font-size:.67rem;text-transform:uppercase;letter-spacing:.08em;color:var(--db-muted);font-weight:700}.crypto-table td{padding:14px 10px}.crypto-asset{display:flex;align-items:center;gap:11px;min-width:175px}.crypto-logo{width:36px;height:36px;border-radius:50%;object-fit:cover;background:var(--db-surface-2);border:1px solid var(--db-border)}.crypto-asset strong{display:block;font-size:.88rem}.crypto-asset small{display:block;color:var(--db-muted);font-size:.7rem;margin-top:2px}.crypto-price{font-weight:700;font-variant-numeric:tabular-nums;white-space:nowrap}.crypto-change{font-weight:700;font-size:.78rem;white-space:nowrap}.crypto-change.up{color:#20c997}.crypto-change.down{color:#ff6b7a}.crypto-spark{width:150px;height:46px;display:block}.crypto-actions{display:flex;justify-content:flex-end;gap:7px}.crypto-actions button{border:0;border-radius:9px;padding:7px 11px;font-size:.72rem;font-weight:700}.crypto-buy{background:rgba(40,100,255,.14);color:#4f82ff}.crypto-sell{background:rgba(255,107,122,.12);color:#ff7180}.crypto-loading{display:flex;justify-content:center;align-items:center;gap:9px;padding:30px;color:var(--db-muted)}.crypto-error{text-align:center;padding:24px;color:var(--db-muted)}.crypto-error i{display:block;font-size:1.5rem;margin-bottom:7px}.crypto-mobile-list{display:none}.crypto-market-foot{display:flex;justify-content:space-between;border-top:1px solid var(--db-border);padding:11px 16px;color:var(--db-muted);font-size:.7rem}.crypto-market-foot i{margin-right:5px;color:var(--db-green)}
@media(max-width:767.98px){.crypto-table-wrap{display:none}.crypto-mobile-list{display:block;padding:0 12px}.crypto-mobile-card{border:1px solid var(--db-border);background:var(--db-surface-2);border-radius:14px;padding:13px;margin-bottom:9px}.crypto-mobile-top,.crypto-mobile-bottom{display:flex;align-items:center;justify-content:space-between;gap:10px}.crypto-mobile-bottom{margin-top:10px}.crypto-mobile-card .crypto-spark{width:105px;height:38px}.crypto-mobile-card .crypto-actions{justify-content:flex-end}.crypto-mobile-card .crypto-actions button{padding:6px 9px}.crypto-market-meta span{display:none}}
</style>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
const rowsEl=document.getElementById('cryptoMarketRows'),mobileEl=document.getElementById('cryptoMobileRows'),refresh=document.getElementById('cryptoRefresh'),updated=document.getElementById('cryptoLastUpdated'),endpoint=@json(route('ajax.crypto'));
const money=n=>{n=Number(n);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:n<1?4:2,maximumFractionDigits:n<1?8:2}).format(n):'—'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function spark(canvas,points,up){const v=(points||[]).map(Number).filter(Number.isFinite);if(v.length<2)return;const d=window.devicePixelRatio||1,w=canvas.clientWidth||150,h=canvas.clientHeight||46;canvas.width=w*d;canvas.height=h*d;const x=canvas.getContext('2d');x.scale(d,d);const min=Math.min(...v),max=Math.max(...v),range=max-min||1;x.beginPath();v.forEach((n,i)=>{const px=i*(w/(v.length-1)),py=h-5-((n-min)/range)*(h-10);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=up?'#20c997':'#ff6b7a';x.lineWidth=2;x.lineJoin='round';x.stroke()}
function bind(){document.querySelectorAll('.crypto-spark').forEach(c=>{try{spark(c,JSON.parse(decodeURIComponent(c.dataset.points||'[]')),c.dataset.up==='1')}catch(e){}});document.querySelectorAll('.crypto-trade').forEach(b=>b.addEventListener('click',()=>alert((b.dataset.action==='buy'?'Buy ':'Sell ')+b.dataset.asset.toUpperCase()+' — live market data is connected. Crypto order execution can be connected to the wallet/order ledger next.')))}
function render(data){if(!Array.isArray(data)||!data.length){rowsEl.innerHTML='<tr><td colspan="5"><div class="crypto-error"><i class="bi bi-bar-chart"></i>No live market data is available right now.</div></td></tr>';mobileEl.innerHTML='';return}let desktop='',mobile='';data.forEach(c=>{const ch=Number(c.price_change_percentage_24h),up=ch>=0,pts=(c.sparkline_in_7d&&c.sparkline_in_7d.price)||[],name=esc(c.name),sym=esc((c.symbol||'').toUpperCase()),id=esc(c.id),img=esc(c.image||'');desktop+='<tr><td><div class="crypto-asset"><img class="crypto-logo" src="'+img+'" alt="'+name+'"><div><strong>'+name+'</strong><small>'+sym+' · #'+esc(c.market_cap_rank||'—')+'</small></div></div></td><td class="crypto-price">'+money(c.current_price)+'</td><td><span class="crypto-change '+(up?'up':'down')+'">'+(up?'+':'')+(Number.isFinite(ch)?ch.toFixed(2):'—')+'%</span></td><td><canvas class="crypto-spark" data-points="'+encodeURIComponent(JSON.stringify(pts))+'" data-up="'+(up?'1':'0')+'"></canvas></td><td><div class="crypto-actions"><button class="crypto-buy crypto-trade" data-action="buy" data-asset="'+id+'">Buy</button><button class="crypto-sell crypto-trade" data-action="sell" data-asset="'+id+'">Sell</button></div></td></tr>';mobile+='<div class="crypto-mobile-card"><div class="crypto-mobile-top"><div class="crypto-asset"><img class="crypto-logo" src="'+img+'" alt="'+name+'"><div><strong>'+name+'</strong><small>'+sym+'</small></div></div><span class="crypto-change '+(up?'up':'down')+'">'+(up?'+':'')+(Number.isFinite(ch)?ch.toFixed(2):'—')+'%</span></div><div class="crypto-mobile-bottom"><div><div class="crypto-price">'+money(c.current_price)+'</div><small style="color:var(--db-muted)">24h</small></div><canvas class="crypto-spark" data-points="'+encodeURIComponent(JSON.stringify(pts))+'" data-up="'+(up?'1':'0')+'"></canvas><div class="crypto-actions"><button class="crypto-buy crypto-trade" data-action="buy" data-asset="'+id+'">Buy</button><button class="crypto-sell crypto-trade" data-action="sell" data-asset="'+id+'">Sell</button></div></div></div>'});rowsEl.innerHTML=desktop;mobileEl.innerHTML=mobile;bind()}
async function load(){try{const r=await fetch(endpoint,{headers:{Accept:'application/json'}}),data=await r.json();if(!r.ok)throw new Error(data.message||'Market feed unavailable');render(data);if(updated)updated.textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(e){rowsEl.innerHTML='<tr><td colspan="5"><div class="crypto-error"><i class="bi bi-cloud-slash"></i>'+esc(e.message||'Market feed is temporarily unavailable.')+'</div></td></tr>';mobileEl.innerHTML='';if(updated)updated.textContent='Update failed'}}
refresh&&refresh.addEventListener('click',load);load();setInterval(load,60000);
});
</script>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
const rows=@json($chart),labels=[],values=[],volumes=[];
rows.forEach(function(row,index){const entries=Object.entries(row||{});let label=String(index+1),value=null,volume=null;entries.forEach(function(pair){const key=pair[0],raw=pair[1],lower=key.toLowerCase(),num=Number(raw);if(/date|time|created|label|day|month/.test(lower)&&raw!==null&&raw!=='')label=String(raw).slice(0,16);if(Number.isFinite(num)){if(/volume|qty|quantity|trade/.test(lower)&&volume===null)volume=num;if(/price|value|balance|portfolio|rate|close|amount/.test(lower)&&value===null)value=num;}});if(value===null){const nums=entries.map(function(p){return Number(p[1]);}).filter(Number.isFinite);if(nums.length)value=nums[nums.length-1];}if(value!==null){labels.push(label);values.push(value);volumes.push(volume===null?Math.abs(value):volume);}});
const ctx=document.getElementById('portfolioChart'),vctx=document.getElementById('volumeChart');
if(!ctx)return;
const gradient=ctx.getContext('2d').createLinearGradient(0,0,0,280);gradient.addColorStop(0,'rgba(31,199,148,.26)');gradient.addColorStop(1,'rgba(31,199,148,0)');
const options={responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{displayColors:false}},scales:{x:{grid:{display:false},ticks:{color:'#7d8799',maxTicksLimit:8}},y:{grid:{color:'rgba(130,145,170,.10)'},ticks:{color:'#7d8799'}}}};
new Chart(ctx,{type:'line',data:{labels:labels,datasets:[{data:values,borderColor:'#1fc794',backgroundColor:gradient,fill:true,borderWidth:2.5,pointRadius:0,pointHoverRadius:5,tension:.35}]},options:options});
new Chart(vctx,{type:'bar',data:{labels:labels,datasets:[{data:volumes,backgroundColor:'rgba(125,135,153,.22)',borderRadius:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}}}});
if(values.length){const last=values[values.length-1],first=values[0],delta=first?((last-first)/Math.abs(first))*100:0;document.getElementById('chartLastValue').textContent=Number(last).toLocaleString(undefined,{maximumFractionDigits:2});document.getElementById('chartChange').textContent=(delta>=0?'+':'')+delta.toFixed(2)+'% over available history';if(delta<0)document.getElementById('chartChange').classList.add('down');}
document.querySelectorAll('.chart-toolbar button').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.chart-toolbar button').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');});});
});
</script>
@endpush,'bi-pie-chart-fill'],['Active Investments',$stats['active_investments'],'','bi-activity'],['Referral Earnings',$stats['referral_earnings'],$investor->curAbbr ?? '
@foreach($metrics as $metric)<div class="col-6 col-xl-3"><div class="stat-card h-100"><div class="stat-icon"><i class="bi {{ $metric[3] }}"></i></div><div class="stat-label">{{ $metric[0] }}</div><div class="stat-value">{{ $metric[2] }}{{ $metric[2] === '' ? number_format($metric[1]) : number_format((float)$metric[1],2) }}</div><div class="stat-foot"><span class="status-dot"></span> Account data</div></div></div>@endforeach
</div>
<div class="row g-3 mb-4">
<div class="col-12 col-xl-9"><section class="trading-card"><div class="trading-card-header"><div><div class="section-kicker">Portfolio performance</div><h2>Market overview</h2></div><div class="chart-toolbar">@foreach(['1D','1W','1M','3M','1Y'] as $range)<button type="button" class="{{ $loop->first ? 'active' : '' }}">{{ $range }}</button>@endforeach</div></div><div class="chart-summary"><div><span class="price-label">Portfolio index</span><strong id="chartLastValue">—</strong></div><div class="chart-change" id="chartChange">Available account history</div></div><div class="main-chart-wrap"><canvas id="portfolioChart"></canvas></div><div class="volume-wrap"><canvas id="volumeChart"></canvas></div><div class="chart-legend"><span><i class="legend-line"></i> Portfolio movement</span><span><i class="legend-volume"></i> Activity</span></div></section></div>
<div class="col-12 col-xl-3"><section class="market-watch-card h-100"><div class="section-kicker">Quick actions</div><h2>Trade center</h2><div class="quick-action-grid"><a href="{{ route('investments.plans') }}"><span><i class="bi bi-lightning-charge-fill"></i></span><strong>Invest</strong><small>Browse plans</small></a><a href="{{ route('deposit') }}"><span><i class="bi bi-arrow-down-left-circle-fill"></i></span><strong>Deposit</strong><small>Add funds</small></a><a href="{{ route('withdraw') }}"><span><i class="bi bi-arrow-up-right-circle-fill"></i></span><strong>Withdraw</strong><small>Move funds</small></a><a href="{{ route('transfer') }}"><span><i class="bi bi-send-fill"></i></span><strong>Transfer</strong><small>Send funds</small></a></div><div class="watchlist-title">Account status</div><div class="account-status"><div><span>Verification</span><strong><i class="bi bi-shield-check"></i> Active</strong></div><div><span>Open positions</span><strong>{{ number_format($stats['active_investments']) }}</strong></div><div><span>Notifications</span><strong>{{ ($notifications ?? collect())->count() }}</strong></div></div></section></div>
</div>
<div class="row g-3 mb-4">
<div class="col-12"><section class="dashboard-panel crypto-market-panel">
<div class="panel-heading crypto-market-heading"><div><div class="section-kicker"><span class="live-pulse"></span> Live market</div><h2>Cryptocurrency prices</h2><p class="crypto-subtitle">Live prices, 24-hour movement and 7-day market trends.</p></div><div class="crypto-market-meta"><span id="cryptoLastUpdated">Updating…</span><button type="button" class="crypto-refresh-btn" id="cryptoRefresh"><i class="bi bi-arrow-clockwise"></i> Refresh</button></div></div>
<div class="table-responsive crypto-table-wrap"><table class="table trading-table crypto-table align-middle mb-0"><thead><tr><th>Asset</th><th>Price</th><th>24h</th><th>Trend · 7D</th><th class="text-end">Trade</th></tr></thead><tbody id="cryptoMarketRows"><tr><td colspan="5"><div class="crypto-loading"><span class="spinner-border spinner-border-sm"></span> Loading live cryptocurrency prices…</div></td></tr></tbody></table></div>
<div class="crypto-mobile-list" id="cryptoMobileRows"></div>
<div class="crypto-market-foot"><span><i class="bi bi-broadcast-pin"></i> Live market data</span><span>Prices shown in USD</span></div>
</section></div></div>
<div class="row g-3">
<div class="col-12 col-xl-8"><section class="dashboard-panel"><div class="panel-heading"><div><div class="section-kicker">Positions</div><h2>Investment activity</h2></div><a href="{{ route('investments.contracts') }}" class="panel-link">View all <i class="bi bi-arrow-up-right"></i></a></div><div class="table-responsive"><table class="table trading-table align-middle"><thead><tr><th>Investment</th><th>Amount</th><th>Start date</th><th>Status</th></tr></thead><tbody>@forelse($contracts as $c)<tr><td><div class="asset-cell"><span class="asset-icon"><i class="bi bi-graph-up"></i></span><div><strong>{{ $c->Plan_Type }}</strong><small>Investment contract</small></div></div></td><td>{{ $investor->curAbbr ?? '$' }}{{ number_format((float)$c->Amount*(float)($investor->exchangerate ?? 1),2) }}</td><td>{{ $c->Contract_Start?->format('M d, Y') ?? '—' }}</td><td><span class="trade-status {{ $c->Status==1?'positive':($c->Status==2?'neutral':'pending') }}">{{ $c->Status==1?'Active':($c->Status==2?'Completed':'Pending') }}</span></td></tr>@empty<tr><td colspan="4" class="empty-state"><i class="bi bi-bar-chart-line"></i><strong>No investments yet</strong><span>Your positions will appear here.</span></td></tr>@endforelse</tbody></table></div></section></div>
</div>
</div>
@endsection
@push('head')
<style>
.crypto-market-panel{overflow:hidden}.crypto-subtitle{margin:.35rem 0 0;color:var(--db-muted);font-size:.84rem}.crypto-market-meta{display:flex;align-items:center;gap:10px;color:var(--db-muted);font-size:.76rem}.crypto-refresh-btn{border:1px solid var(--db-border);background:var(--db-surface-2);color:var(--db-text);border-radius:9px;padding:7px 10px;font-size:.76rem}.crypto-refresh-btn:hover{color:var(--db-green)}
.crypto-table{min-width:850px}.crypto-table th{font-size:.67rem;text-transform:uppercase;letter-spacing:.08em;color:var(--db-muted);font-weight:700}.crypto-table td{padding:14px 10px}.crypto-asset{display:flex;align-items:center;gap:11px;min-width:175px}.crypto-logo{width:36px;height:36px;border-radius:50%;object-fit:cover;background:var(--db-surface-2);border:1px solid var(--db-border)}.crypto-asset strong{display:block;font-size:.88rem}.crypto-asset small{display:block;color:var(--db-muted);font-size:.7rem;margin-top:2px}.crypto-price{font-weight:700;font-variant-numeric:tabular-nums;white-space:nowrap}.crypto-change{font-weight:700;font-size:.78rem;white-space:nowrap}.crypto-change.up{color:#20c997}.crypto-change.down{color:#ff6b7a}.crypto-spark{width:150px;height:46px;display:block}.crypto-actions{display:flex;justify-content:flex-end;gap:7px}.crypto-actions button{border:0;border-radius:9px;padding:7px 11px;font-size:.72rem;font-weight:700}.crypto-buy{background:rgba(40,100,255,.14);color:#4f82ff}.crypto-sell{background:rgba(255,107,122,.12);color:#ff7180}.crypto-loading{display:flex;justify-content:center;align-items:center;gap:9px;padding:30px;color:var(--db-muted)}.crypto-error{text-align:center;padding:24px;color:var(--db-muted)}.crypto-error i{display:block;font-size:1.5rem;margin-bottom:7px}.crypto-mobile-list{display:none}.crypto-market-foot{display:flex;justify-content:space-between;border-top:1px solid var(--db-border);padding:11px 16px;color:var(--db-muted);font-size:.7rem}.crypto-market-foot i{margin-right:5px;color:var(--db-green)}
@media(max-width:767.98px){.crypto-table-wrap{display:none}.crypto-mobile-list{display:block;padding:0 12px}.crypto-mobile-card{border:1px solid var(--db-border);background:var(--db-surface-2);border-radius:14px;padding:13px;margin-bottom:9px}.crypto-mobile-top,.crypto-mobile-bottom{display:flex;align-items:center;justify-content:space-between;gap:10px}.crypto-mobile-bottom{margin-top:10px}.crypto-mobile-card .crypto-spark{width:105px;height:38px}.crypto-mobile-card .crypto-actions{justify-content:flex-end}.crypto-mobile-card .crypto-actions button{padding:6px 9px}.crypto-market-meta span{display:none}}
</style>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
const rowsEl=document.getElementById('cryptoMarketRows'),mobileEl=document.getElementById('cryptoMobileRows'),refresh=document.getElementById('cryptoRefresh'),updated=document.getElementById('cryptoLastUpdated'),endpoint=@json(route('ajax.crypto'));
const money=n=>{n=Number(n);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:n<1?4:2,maximumFractionDigits:n<1?8:2}).format(n):'—'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function spark(canvas,points,up){const v=(points||[]).map(Number).filter(Number.isFinite);if(v.length<2)return;const d=window.devicePixelRatio||1,w=canvas.clientWidth||150,h=canvas.clientHeight||46;canvas.width=w*d;canvas.height=h*d;const x=canvas.getContext('2d');x.scale(d,d);const min=Math.min(...v),max=Math.max(...v),range=max-min||1;x.beginPath();v.forEach((n,i)=>{const px=i*(w/(v.length-1)),py=h-5-((n-min)/range)*(h-10);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=up?'#20c997':'#ff6b7a';x.lineWidth=2;x.lineJoin='round';x.stroke()}
function bind(){document.querySelectorAll('.crypto-spark').forEach(c=>{try{spark(c,JSON.parse(decodeURIComponent(c.dataset.points||'[]')),c.dataset.up==='1')}catch(e){}});document.querySelectorAll('.crypto-trade').forEach(b=>b.addEventListener('click',()=>alert((b.dataset.action==='buy'?'Buy ':'Sell ')+b.dataset.asset.toUpperCase()+' — live market data is connected. Crypto order execution can be connected to the wallet/order ledger next.')))}
function render(data){if(!Array.isArray(data)||!data.length){rowsEl.innerHTML='<tr><td colspan="5"><div class="crypto-error"><i class="bi bi-bar-chart"></i>No live market data is available right now.</div></td></tr>';mobileEl.innerHTML='';return}let desktop='',mobile='';data.forEach(c=>{const ch=Number(c.price_change_percentage_24h),up=ch>=0,pts=(c.sparkline_in_7d&&c.sparkline_in_7d.price)||[],name=esc(c.name),sym=esc((c.symbol||'').toUpperCase()),id=esc(c.id),img=esc(c.image||'');desktop+='<tr><td><div class="crypto-asset"><img class="crypto-logo" src="'+img+'" alt="'+name+'"><div><strong>'+name+'</strong><small>'+sym+' · #'+esc(c.market_cap_rank||'—')+'</small></div></div></td><td class="crypto-price">'+money(c.current_price)+'</td><td><span class="crypto-change '+(up?'up':'down')+'">'+(up?'+':'')+(Number.isFinite(ch)?ch.toFixed(2):'—')+'%</span></td><td><canvas class="crypto-spark" data-points="'+encodeURIComponent(JSON.stringify(pts))+'" data-up="'+(up?'1':'0')+'"></canvas></td><td><div class="crypto-actions"><button class="crypto-buy crypto-trade" data-action="buy" data-asset="'+id+'">Buy</button><button class="crypto-sell crypto-trade" data-action="sell" data-asset="'+id+'">Sell</button></div></td></tr>';mobile+='<div class="crypto-mobile-card"><div class="crypto-mobile-top"><div class="crypto-asset"><img class="crypto-logo" src="'+img+'" alt="'+name+'"><div><strong>'+name+'</strong><small>'+sym+'</small></div></div><span class="crypto-change '+(up?'up':'down')+'">'+(up?'+':'')+(Number.isFinite(ch)?ch.toFixed(2):'—')+'%</span></div><div class="crypto-mobile-bottom"><div><div class="crypto-price">'+money(c.current_price)+'</div><small style="color:var(--db-muted)">24h</small></div><canvas class="crypto-spark" data-points="'+encodeURIComponent(JSON.stringify(pts))+'" data-up="'+(up?'1':'0')+'"></canvas><div class="crypto-actions"><button class="crypto-buy crypto-trade" data-action="buy" data-asset="'+id+'">Buy</button><button class="crypto-sell crypto-trade" data-action="sell" data-asset="'+id+'">Sell</button></div></div></div>'});rowsEl.innerHTML=desktop;mobileEl.innerHTML=mobile;bind()}
async function load(){try{const r=await fetch(endpoint,{headers:{Accept:'application/json'}}),data=await r.json();if(!r.ok)throw new Error(data.message||'Market feed unavailable');render(data);if(updated)updated.textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(e){rowsEl.innerHTML='<tr><td colspan="5"><div class="crypto-error"><i class="bi bi-cloud-slash"></i>'+esc(e.message||'Market feed is temporarily unavailable.')+'</div></td></tr>';mobileEl.innerHTML='';if(updated)updated.textContent='Update failed'}}
refresh&&refresh.addEventListener('click',load);load();setInterval(load,60000);
});
</script>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
const rows=@json($chart),labels=[],values=[],volumes=[];
rows.forEach(function(row,index){const entries=Object.entries(row||{});let label=String(index+1),value=null,volume=null;entries.forEach(function(pair){const key=pair[0],raw=pair[1],lower=key.toLowerCase(),num=Number(raw);if(/date|time|created|label|day|month/.test(lower)&&raw!==null&&raw!=='')label=String(raw).slice(0,16);if(Number.isFinite(num)){if(/volume|qty|quantity|trade/.test(lower)&&volume===null)volume=num;if(/price|value|balance|portfolio|rate|close|amount/.test(lower)&&value===null)value=num;}});if(value===null){const nums=entries.map(function(p){return Number(p[1]);}).filter(Number.isFinite);if(nums.length)value=nums[nums.length-1];}if(value!==null){labels.push(label);values.push(value);volumes.push(volume===null?Math.abs(value):volume);}});
const ctx=document.getElementById('portfolioChart'),vctx=document.getElementById('volumeChart');
if(!ctx)return;
const gradient=ctx.getContext('2d').createLinearGradient(0,0,0,280);gradient.addColorStop(0,'rgba(31,199,148,.26)');gradient.addColorStop(1,'rgba(31,199,148,0)');
const options={responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{displayColors:false}},scales:{x:{grid:{display:false},ticks:{color:'#7d8799',maxTicksLimit:8}},y:{grid:{color:'rgba(130,145,170,.10)'},ticks:{color:'#7d8799'}}}};
new Chart(ctx,{type:'line',data:{labels:labels,datasets:[{data:values,borderColor:'#1fc794',backgroundColor:gradient,fill:true,borderWidth:2.5,pointRadius:0,pointHoverRadius:5,tension:.35}]},options:options});
new Chart(vctx,{type:'bar',data:{labels:labels,datasets:[{data:volumes,backgroundColor:'rgba(125,135,153,.22)',borderRadius:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}}}});
if(values.length){const last=values[values.length-1],first=values[0],delta=first?((last-first)/Math.abs(first))*100:0;document.getElementById('chartLastValue').textContent=Number(last).toLocaleString(undefined,{maximumFractionDigits:2});document.getElementById('chartChange').textContent=(delta>=0?'+':'')+delta.toFixed(2)+'% over available history';if(delta<0)document.getElementById('chartChange').classList.add('down');}
document.querySelectorAll('.chart-toolbar button').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.chart-toolbar button').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');});});
});
</script>
@endpush,'bi-people-fill']]; @endphp
@foreach($metrics as $metric)<div class="col-6 col-xl-3"><div class="stat-card h-100"><div class="stat-icon"><i class="bi {{ $metric[3] }}"></i></div><div class="stat-label">{{ $metric[0] }}</div><div class="stat-value">{{ $metric[2] }}{{ $metric[2] === '' ? number_format($metric[1]) : number_format((float)$metric[1],2) }}</div><div class="stat-foot"><span class="status-dot"></span> Account data</div></div></div>@endforeach
</div>
<div class="row g-3 mb-4">
<div class="col-12 col-xl-9"><section class="trading-card"><div class="trading-card-header"><div><div class="section-kicker">Portfolio performance</div><h2>Market overview</h2></div><div class="chart-toolbar">@foreach(['1D','1W','1M','3M','1Y'] as $range)<button type="button" class="{{ $loop->first ? 'active' : '' }}">{{ $range }}</button>@endforeach</div></div><div class="chart-summary"><div><span class="price-label">Portfolio index</span><strong id="chartLastValue">—</strong></div><div class="chart-change" id="chartChange">Available account history</div></div><div class="main-chart-wrap"><canvas id="portfolioChart"></canvas></div><div class="volume-wrap"><canvas id="volumeChart"></canvas></div><div class="chart-legend"><span><i class="legend-line"></i> Portfolio movement</span><span><i class="legend-volume"></i> Activity</span></div></section></div>
<div class="col-12 col-xl-3"><section class="market-watch-card h-100"><div class="section-kicker">Quick actions</div><h2>Trade center</h2><div class="quick-action-grid"><a href="{{ route('investments.plans') }}"><span><i class="bi bi-lightning-charge-fill"></i></span><strong>Invest</strong><small>Browse plans</small></a><a href="{{ route('deposit') }}"><span><i class="bi bi-arrow-down-left-circle-fill"></i></span><strong>Deposit</strong><small>Add funds</small></a><a href="{{ route('withdraw') }}"><span><i class="bi bi-arrow-up-right-circle-fill"></i></span><strong>Withdraw</strong><small>Move funds</small></a><a href="{{ route('transfer') }}"><span><i class="bi bi-send-fill"></i></span><strong>Transfer</strong><small>Send funds</small></a></div><div class="watchlist-title">Account status</div><div class="account-status"><div><span>Verification</span><strong><i class="bi bi-shield-check"></i> Active</strong></div><div><span>Open positions</span><strong>{{ number_format($stats['active_investments']) }}</strong></div><div><span>Notifications</span><strong>{{ ($notifications ?? collect())->count() }}</strong></div></div></section></div>
</div>
<div class="row g-3 mb-4">
<div class="col-12"><section class="dashboard-panel crypto-market-panel">
<div class="panel-heading crypto-market-heading"><div><div class="section-kicker"><span class="live-pulse"></span> Live market</div><h2>Cryptocurrency prices</h2><p class="crypto-subtitle">Live prices, 24-hour movement and 7-day market trends.</p></div><div class="crypto-market-meta"><span id="cryptoLastUpdated">Updating…</span><button type="button" class="crypto-refresh-btn" id="cryptoRefresh"><i class="bi bi-arrow-clockwise"></i> Refresh</button></div></div>
<div class="table-responsive crypto-table-wrap"><table class="table trading-table crypto-table align-middle mb-0"><thead><tr><th>Asset</th><th>Price</th><th>24h</th><th>Trend · 7D</th><th class="text-end">Trade</th></tr></thead><tbody id="cryptoMarketRows"><tr><td colspan="5"><div class="crypto-loading"><span class="spinner-border spinner-border-sm"></span> Loading live cryptocurrency prices…</div></td></tr></tbody></table></div>
<div class="crypto-mobile-list" id="cryptoMobileRows"></div>
<div class="crypto-market-foot"><span><i class="bi bi-broadcast-pin"></i> Live market data</span><span>Prices shown in USD</span></div>
</section></div></div>
<div class="row g-3">
<div class="col-12 col-xl-8"><section class="dashboard-panel"><div class="panel-heading"><div><div class="section-kicker">Positions</div><h2>Investment activity</h2></div><a href="{{ route('investments.contracts') }}" class="panel-link">View all <i class="bi bi-arrow-up-right"></i></a></div><div class="table-responsive"><table class="table trading-table align-middle"><thead><tr><th>Investment</th><th>Amount</th><th>Start date</th><th>Status</th></tr></thead><tbody>@forelse($contracts as $c)<tr><td><div class="asset-cell"><span class="asset-icon"><i class="bi bi-graph-up"></i></span><div><strong>{{ $c->Plan_Type }}</strong><small>Investment contract</small></div></div></td><td>{{ $investor->curAbbr ?? '$' }}{{ number_format((float)$c->Amount*(float)($investor->exchangerate ?? 1),2) }}</td><td>{{ $c->Contract_Start?->format('M d, Y') ?? '—' }}</td><td><span class="trade-status {{ $c->Status==1?'positive':($c->Status==2?'neutral':'pending') }}">{{ $c->Status==1?'Active':($c->Status==2?'Completed':'Pending') }}</span></td></tr>@empty<tr><td colspan="4" class="empty-state"><i class="bi bi-bar-chart-line"></i><strong>No investments yet</strong><span>Your positions will appear here.</span></td></tr>@endforelse</tbody></table></div></section></div>
</div>
</div>
@endsection
@push('head')
<style>
.crypto-market-panel{overflow:hidden}.crypto-subtitle{margin:.35rem 0 0;color:var(--db-muted);font-size:.84rem}.crypto-market-meta{display:flex;align-items:center;gap:10px;color:var(--db-muted);font-size:.76rem}.crypto-refresh-btn{border:1px solid var(--db-border);background:var(--db-surface-2);color:var(--db-text);border-radius:9px;padding:7px 10px;font-size:.76rem}.crypto-refresh-btn:hover{color:var(--db-green)}
.crypto-table{min-width:850px}.crypto-table th{font-size:.67rem;text-transform:uppercase;letter-spacing:.08em;color:var(--db-muted);font-weight:700}.crypto-table td{padding:14px 10px}.crypto-asset{display:flex;align-items:center;gap:11px;min-width:175px}.crypto-logo{width:36px;height:36px;border-radius:50%;object-fit:cover;background:var(--db-surface-2);border:1px solid var(--db-border)}.crypto-asset strong{display:block;font-size:.88rem}.crypto-asset small{display:block;color:var(--db-muted);font-size:.7rem;margin-top:2px}.crypto-price{font-weight:700;font-variant-numeric:tabular-nums;white-space:nowrap}.crypto-change{font-weight:700;font-size:.78rem;white-space:nowrap}.crypto-change.up{color:#20c997}.crypto-change.down{color:#ff6b7a}.crypto-spark{width:150px;height:46px;display:block}.crypto-actions{display:flex;justify-content:flex-end;gap:7px}.crypto-actions button{border:0;border-radius:9px;padding:7px 11px;font-size:.72rem;font-weight:700}.crypto-buy{background:rgba(40,100,255,.14);color:#4f82ff}.crypto-sell{background:rgba(255,107,122,.12);color:#ff7180}.crypto-loading{display:flex;justify-content:center;align-items:center;gap:9px;padding:30px;color:var(--db-muted)}.crypto-error{text-align:center;padding:24px;color:var(--db-muted)}.crypto-error i{display:block;font-size:1.5rem;margin-bottom:7px}.crypto-mobile-list{display:none}.crypto-market-foot{display:flex;justify-content:space-between;border-top:1px solid var(--db-border);padding:11px 16px;color:var(--db-muted);font-size:.7rem}.crypto-market-foot i{margin-right:5px;color:var(--db-green)}
@media(max-width:767.98px){.crypto-table-wrap{display:none}.crypto-mobile-list{display:block;padding:0 12px}.crypto-mobile-card{border:1px solid var(--db-border);background:var(--db-surface-2);border-radius:14px;padding:13px;margin-bottom:9px}.crypto-mobile-top,.crypto-mobile-bottom{display:flex;align-items:center;justify-content:space-between;gap:10px}.crypto-mobile-bottom{margin-top:10px}.crypto-mobile-card .crypto-spark{width:105px;height:38px}.crypto-mobile-card .crypto-actions{justify-content:flex-end}.crypto-mobile-card .crypto-actions button{padding:6px 9px}.crypto-market-meta span{display:none}}
</style>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
const rowsEl=document.getElementById('cryptoMarketRows'),mobileEl=document.getElementById('cryptoMobileRows'),refresh=document.getElementById('cryptoRefresh'),updated=document.getElementById('cryptoLastUpdated'),endpoint=@json(route('ajax.crypto'));
const money=n=>{n=Number(n);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:n<1?4:2,maximumFractionDigits:n<1?8:2}).format(n):'—'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function spark(canvas,points,up){const v=(points||[]).map(Number).filter(Number.isFinite);if(v.length<2)return;const d=window.devicePixelRatio||1,w=canvas.clientWidth||150,h=canvas.clientHeight||46;canvas.width=w*d;canvas.height=h*d;const x=canvas.getContext('2d');x.scale(d,d);const min=Math.min(...v),max=Math.max(...v),range=max-min||1;x.beginPath();v.forEach((n,i)=>{const px=i*(w/(v.length-1)),py=h-5-((n-min)/range)*(h-10);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=up?'#20c997':'#ff6b7a';x.lineWidth=2;x.lineJoin='round';x.stroke()}
function bind(){document.querySelectorAll('.crypto-spark').forEach(c=>{try{spark(c,JSON.parse(decodeURIComponent(c.dataset.points||'[]')),c.dataset.up==='1')}catch(e){}});document.querySelectorAll('.crypto-trade').forEach(b=>b.addEventListener('click',()=>alert((b.dataset.action==='buy'?'Buy ':'Sell ')+b.dataset.asset.toUpperCase()+' — live market data is connected. Crypto order execution can be connected to the wallet/order ledger next.')))}
function render(data){if(!Array.isArray(data)||!data.length){rowsEl.innerHTML='<tr><td colspan="5"><div class="crypto-error"><i class="bi bi-bar-chart"></i>No live market data is available right now.</div></td></tr>';mobileEl.innerHTML='';return}let desktop='',mobile='';data.forEach(c=>{const ch=Number(c.price_change_percentage_24h),up=ch>=0,pts=(c.sparkline_in_7d&&c.sparkline_in_7d.price)||[],name=esc(c.name),sym=esc((c.symbol||'').toUpperCase()),id=esc(c.id),img=esc(c.image||'');desktop+='<tr><td><div class="crypto-asset"><img class="crypto-logo" src="'+img+'" alt="'+name+'"><div><strong>'+name+'</strong><small>'+sym+' · #'+esc(c.market_cap_rank||'—')+'</small></div></div></td><td class="crypto-price">'+money(c.current_price)+'</td><td><span class="crypto-change '+(up?'up':'down')+'">'+(up?'+':'')+(Number.isFinite(ch)?ch.toFixed(2):'—')+'%</span></td><td><canvas class="crypto-spark" data-points="'+encodeURIComponent(JSON.stringify(pts))+'" data-up="'+(up?'1':'0')+'"></canvas></td><td><div class="crypto-actions"><button class="crypto-buy crypto-trade" data-action="buy" data-asset="'+id+'">Buy</button><button class="crypto-sell crypto-trade" data-action="sell" data-asset="'+id+'">Sell</button></div></td></tr>';mobile+='<div class="crypto-mobile-card"><div class="crypto-mobile-top"><div class="crypto-asset"><img class="crypto-logo" src="'+img+'" alt="'+name+'"><div><strong>'+name+'</strong><small>'+sym+'</small></div></div><span class="crypto-change '+(up?'up':'down')+'">'+(up?'+':'')+(Number.isFinite(ch)?ch.toFixed(2):'—')+'%</span></div><div class="crypto-mobile-bottom"><div><div class="crypto-price">'+money(c.current_price)+'</div><small style="color:var(--db-muted)">24h</small></div><canvas class="crypto-spark" data-points="'+encodeURIComponent(JSON.stringify(pts))+'" data-up="'+(up?'1':'0')+'"></canvas><div class="crypto-actions"><button class="crypto-buy crypto-trade" data-action="buy" data-asset="'+id+'">Buy</button><button class="crypto-sell crypto-trade" data-action="sell" data-asset="'+id+'">Sell</button></div></div></div>'});rowsEl.innerHTML=desktop;mobileEl.innerHTML=mobile;bind()}
async function load(){try{const r=await fetch(endpoint,{headers:{Accept:'application/json'}}),data=await r.json();if(!r.ok)throw new Error(data.message||'Market feed unavailable');render(data);if(updated)updated.textContent='Updated '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(e){rowsEl.innerHTML='<tr><td colspan="5"><div class="crypto-error"><i class="bi bi-cloud-slash"></i>'+esc(e.message||'Market feed is temporarily unavailable.')+'</div></td></tr>';mobileEl.innerHTML='';if(updated)updated.textContent='Update failed'}}
refresh&&refresh.addEventListener('click',load);load();setInterval(load,60000);
});
</script>
@endpush
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',function(){
const rows=@json($chart),labels=[],values=[],volumes=[];
rows.forEach(function(row,index){const entries=Object.entries(row||{});let label=String(index+1),value=null,volume=null;entries.forEach(function(pair){const key=pair[0],raw=pair[1],lower=key.toLowerCase(),num=Number(raw);if(/date|time|created|label|day|month/.test(lower)&&raw!==null&&raw!=='')label=String(raw).slice(0,16);if(Number.isFinite(num)){if(/volume|qty|quantity|trade/.test(lower)&&volume===null)volume=num;if(/price|value|balance|portfolio|rate|close|amount/.test(lower)&&value===null)value=num;}});if(value===null){const nums=entries.map(function(p){return Number(p[1]);}).filter(Number.isFinite);if(nums.length)value=nums[nums.length-1];}if(value!==null){labels.push(label);values.push(value);volumes.push(volume===null?Math.abs(value):volume);}});
const ctx=document.getElementById('portfolioChart'),vctx=document.getElementById('volumeChart');
if(!ctx)return;
const gradient=ctx.getContext('2d').createLinearGradient(0,0,0,280);gradient.addColorStop(0,'rgba(31,199,148,.26)');gradient.addColorStop(1,'rgba(31,199,148,0)');
const options={responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{displayColors:false}},scales:{x:{grid:{display:false},ticks:{color:'#7d8799',maxTicksLimit:8}},y:{grid:{color:'rgba(130,145,170,.10)'},ticks:{color:'#7d8799'}}}};
new Chart(ctx,{type:'line',data:{labels:labels,datasets:[{data:values,borderColor:'#1fc794',backgroundColor:gradient,fill:true,borderWidth:2.5,pointRadius:0,pointHoverRadius:5,tension:.35}]},options:options});
new Chart(vctx,{type:'bar',data:{labels:labels,datasets:[{data:volumes,backgroundColor:'rgba(125,135,153,.22)',borderRadius:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}}}});
if(values.length){const last=values[values.length-1],first=values[0],delta=first?((last-first)/Math.abs(first))*100:0;document.getElementById('chartLastValue').textContent=Number(last).toLocaleString(undefined,{maximumFractionDigits:2});document.getElementById('chartChange').textContent=(delta>=0?'+':'')+delta.toFixed(2)+'% over available history';if(delta<0)document.getElementById('chartChange').classList.add('down');}
document.querySelectorAll('.chart-toolbar button').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.chart-toolbar button').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');});});
});
</script>
@endpush