@extends('layouts.app')
@section('title','Transfer')
@section('heading','Transfer')
@section('content')
<div class="card table-card mb-4"><div class="card-body"><h5>Transfer history</h5><div class="table-responsive"><table class="table"><thead><tr><th>Counterparty</th><th>Amount</th><th>Type</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>
@forelse($transfers as $t)<tr><td>{{ $t->Transferer===$investor->Investor_id ? $t->Name : $t->Transferer }}</td><td>{{ $investor->curAbbr }}{{ number_format($t->Amount*(float)$investor->exchangerate,2) }}</td><td>{{ $t->Transferer===$investor->Investor_id?'Transfer out':'Transfer in' }}</td><td>{{ $t->Status?'Success':'Pending' }}</td><td>{{ $t->Date }}</td><td>@if($t->Receiver===$investor->Investor_id && !$t->Status)<button class="btn btn-sm btn-brand confirmTransfer" data-id="{{ $t->id }}" data-amount="{{ $t->Amount }}" data-transferer="{{ $t->Transferer }}" data-receiver="{{ $t->Receiver }}">Confirm</button>@endif</td></tr>@empty<tr><td colspan="6">No transfers yet.</td></tr>@endforelse
</tbody></table></div></div></div><div class="row"><div class="col-lg-6"><div class="card table-card"><div class="card-body"><h5>Send funds</h5><form id="transferForm">@csrf<div class="form-group"><label>Receiver Investor ID</label><div class="input-group"><input name="receiver" class="form-control" required><div class="input-group-append"><button type="button" id="verify" class="btn btn-outline-secondary">Verify</button></div></div><small id="receiverStatus" class="form-text"></small></div><div class="form-group"><label>Amount</label><input name="amount" type="number" step="0.01" class="form-control" required></div><input type="hidden" name="receiver_name" id="receiver_name"><button class="btn btn-brand">Initiate transfer</button></form><div id="msg" class="small mt-3"></div></div></div></div><div class="col-lg-6"><div class="card table-card"><div class="card-body"><h5>Available balance</h5><div class="value">{{ $investor->curAbbr }}{{ number_format($investor->Total_Deposit*(float)$investor->exchangerate,2) }}</div></div></div></div></div>
@endsection
@push('scripts')<script>
document.getElementById('verify').onclick=async()=>{const receiver=document.querySelector('[name=receiver]').value;try{const d=await api('{{ route('transfer.verify') }}',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({receiver})});document.getElementById('receiverStatus').textContent=d.name;document.getElementById('receiver_name').value=d.name}catch(e){document.getElementById('receiverStatus').textContent=e.message}};
document.querySelectorAll('.confirmTransfer').forEach(b=>b.onclick=async()=>{try{const d=await api('{{ route('transfer.confirm') }}',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:b.dataset.amount,receiver:b.dataset.receiver,transferer:b.dataset.transferer})});alert(d.message);location.reload()}catch(e){alert(e.message)}});document.getElementById('transferForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('{{ route('transfer.store') }}',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))});document.getElementById('msg').innerHTML='<span class="text-success">'+d.message+'</span>'}catch(x){document.getElementById('msg').innerHTML='<span class="text-danger">'+x.message+'</span>'}};
</script>@endpush